version: '3'
services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vote-candidate
    ports:
      - '5450:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
